version: '3'
services:
  redis:
    image: redis
  app:
    build: .
    command: bundle exec rackup -o 0.0.0.0 -p 4567
    volumes:
      - .:/exchange-rate-converter
    ports:
      - "4567:4567"
    depends_on:
      - redis
    environment:
      - RACK_ENV=production
      - REDIS_URL=redis://redis:6379/0